# Generated by Django 6.0.7 on 2026-08-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_amount_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Pay Online')], default='online', max_length=20),
        ),
    ]
