# Generated by Django 6.0.7 on 2026-09-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paystack_reference',
            new_name='tx_ref',
        ),
    ]
